### ISSUE TITLE
Missing times

### ISSUE THREAD

**Issue by aasensio** [dfouhey/sdodemo#1]
There seems to be of the order of 10k missing observations in the range 2011 to 2018. Is this inherited from the large DB?

**Comment by dfouhey** [comment]
Github didn't send me an email when this got raised (somehow the repo was not set to watch...). I'm really sorry about that!

It's answered now on the FAQ (and by email), but for the record: SDO itself will have some missing observations due to calibration maneuvers and anomalies. To prevent ambiguity in the handling of partial observations and to prevent apples-to-oranges experiments, Mini SDO has only full observations. The full dataset has the partial observations (i.e., if there's a 8/12 observation, the 8 valid ones are there).
